sudo: false
language: node_js
node_js: node

env:
  - ELM_VERSION=0.18.0 ELM_TEST=0.18.12

cache:
  directories:
    - elm-stuff/build-artifacts
    - elm-stuff/packages
    - tests/elm-stuff/build-artifacts
    - tests/elm-stuff/packages
    - sysconfcpus
    - $HOME/.npm

before_install:
  - npm i -g npm@3
  - |
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi

install:
  - npm install -g elm@$ELM_VERSION elm-test@$ELM_TEST

script:
  - elm-test --verbose
after_success:
  - git config --replace-all remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  - git fetch --tags
  - npm run semantic-release
